name: Strike
version: 1.3.2
main: me.luminescence.strike.Main
api-version: 1.16
authors: [Luminescence]
description: This plugin makes lightning fun!
commands:
  strike:
    description: This command will strike a player with lightning!
    permission: strike.strike
    permission-message: You cannot do this!
  lstick:
    description: This command gives you a lightning stick to strike everwhere!
    permission: strike.strike
    permission-message: You cannot do this!
  reloadconfig:
    description: Reloads the configuration file of Strike.
    permission: strike.strike
    permission-message: You cannot do this!
  strikethere:
    description: Strikes where you are aiming!
    permission: strike.strike
    permission-message: You cannot do this!
  strikeall:
    description: Strikes all players online!
    permission: strike.strike
    permission-message: You cannot do this!

